-- MySQL Script generated by MySQL Workbench
-- Thu May 14 01:27:23 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tpc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tpc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tpc` DEFAULT CHARACTER SET utf8 ;
USE `tpc` ;

-- -----------------------------------------------------
-- Table `tpc`.`sistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpc`.`sistema` (
  `idSistema` INT NOT NULL,
  PRIMARY KEY (`idSistema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpc`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpc`.`producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `estado` BIT(1) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `precioUnitario` DOUBLE NOT NULL,
  `fechaAlta` DATE NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `idSistema` INT(11) NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fkSistema4_idx` (`idSistema` ASC) VISIBLE,
  CONSTRAINT `fkSistema4`
    FOREIGN KEY (`idSistema`)
    REFERENCES `tpc`.`sistema` (`idSistema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpc`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpc`.`pedido` (
  `cantidad` INT NOT NULL,
  `aceptado` BIT(1) NOT NULL,
  `idPedido` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  CONSTRAINT `fkProducto`
    FOREIGN KEY (`idPedido`)
    REFERENCES `tpc`.`producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpc`.`sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpc`.`sucursal` (
  `idSucursal` INT(11) NOT NULL,
  `telefono` INT(12) NOT NULL,
  `idSistema` INT(11) NOT NULL,
  PRIMARY KEY (`idSucursal`),
  INDEX `fkSistema_idx` (`idSistema` ASC) VISIBLE,
  CONSTRAINT `fkSistema`
    FOREIGN KEY (`idSistema`)
    REFERENCES `tpc`.`sistema` (`idSistema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpc`.`lote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpc`.`lote` (
  `cantidad` INT NOT NULL,
  `cantidadTotal` INT NOT NULL,
  `fechaDeIngreso` DATE NOT NULL,
  `idLote` INT NOT NULL,
  `idProducto` INT(11) NOT NULL,
  PRIMARY KEY (`idLote`),
  INDEX `fkProducto_2_idx` (`idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_sucursal_3`
    FOREIGN KEY (`idLote`)
    REFERENCES `tpc`.`sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkProducto_2`
    FOREIGN KEY (`idProducto`)
    REFERENCES `tpc`.`producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpc`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpc`.`persona` (
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `fechaNacimiento` DATE NULL DEFAULT NULL,
  `dni` INT(11) NOT NULL,
  `idPersona` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpc`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpc`.`empleado` (
  `horasPorJornada` TIME NOT NULL,
  `sueldoBasico` DOUBLE NOT NULL,
  `idEmpleado` INT NOT NULL,
  PRIMARY KEY (`idEmpleado`),
  CONSTRAINT `fk_persona_1`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `tpc`.`persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpc`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpc`.`cliente` (
  `mail` VARCHAR(45) NOT NULL,
  `idCliente` INT NOT NULL,
  `idSistema` INT(11) NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fkSistema3_idx` (`idSistema` ASC) VISIBLE,
  CONSTRAINT `fk_persona`
    FOREIGN KEY (`idCliente`)
    REFERENCES `tpc`.`persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkSistema3`
    FOREIGN KEY (`idSistema`)
    REFERENCES `tpc`.`sistema` (`idSistema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpc`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpc`.`vendedor` (
  `plus` DOUBLE NOT NULL,
  `idVendedor` INT NOT NULL,
  `idSucursal` INT(11) NOT NULL,
  PRIMARY KEY (`idVendedor`),
  INDEX `fk_sucursal_2_idx` (`idSucursal` ASC) VISIBLE,
  CONSTRAINT `fk_empleado`
    FOREIGN KEY (`idVendedor`)
    REFERENCES `tpc`.`empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sucursal_2`
    FOREIGN KEY (`idSucursal`)
    REFERENCES `tpc`.`sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpc`.`gerente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpc`.`gerente` (
  `idGerente` INT NOT NULL,
  PRIMARY KEY (`idGerente`),
  CONSTRAINT `fk_empleado_1`
    FOREIGN KEY (`idGerente`)
    REFERENCES `tpc`.`empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sucursal_1`
    FOREIGN KEY (`idGerente`)
    REFERENCES `tpc`.`sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpc`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpc`.`direccion` (
  `ciudad` VARCHAR(45) NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `latitud` DOUBLE NOT NULL,
  `longitud` DOUBLE NOT NULL,
  `idDireccion` INT(11) NOT NULL,
  PRIMARY KEY (`idDireccion`),
  CONSTRAINT `fk_sucursal`
    FOREIGN KEY (`idDireccion`)
    REFERENCES `tpc`.`sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpc`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpc`.`venta` (
  `nroVenta` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `precioTotal` DOUBLE NOT NULL,
  `idVenta` INT NOT NULL,
  `idSistema` INT(11) NOT NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `fkSistema2_idx` (`idSistema` ASC) VISIBLE,
  CONSTRAINT `fkSistema2`
    FOREIGN KEY (`idSistema`)
    REFERENCES `tpc`.`sistema` (`idSistema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpc`.`vendedorxventa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpc`.`vendedorxventa` (
  `idVendedor` INT NOT NULL,
  `idVenta` INT NOT NULL,
  INDEX `fk_Vendedor_idx` (`idVendedor` ASC) VISIBLE,
  INDEX `fk_Venta_idx` (`idVenta` ASC) VISIBLE,
  CONSTRAINT `fk_Vendedor`
    FOREIGN KEY (`idVendedor`)
    REFERENCES `tpc`.`vendedor` (`idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta`
    FOREIGN KEY (`idVenta`)
    REFERENCES `tpc`.`venta` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpc`.`ventaxpedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpc`.`ventaxpedido` (
  `idVenta` INT NOT NULL,
  `idPedido` INT NOT NULL,
  INDEX `fk_venta_3_idx` (`idVenta` ASC) VISIBLE,
  INDEX `fk_pedido_3_idx` (`idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_venta_3`
    FOREIGN KEY (`idVenta`)
    REFERENCES `tpc`.`venta` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_3`
    FOREIGN KEY (`idPedido`)
    REFERENCES `tpc`.`pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
